name: Local Solution Promotion

on:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

permissions:
  contents: read

jobs:

  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipx
        pipx install https://github.com/instabase/app-cicd-toolkit/releases/download/0.0.2/instabase_app_cicd_toolkit-0.0.2-py3-none-any.whl
    - name: Upload and compile IB solution
      env:
        TARGET_IB_API_TOKEN: ${{ secrets.TARGET_IB_API_TOKEN }}
        SOURCE_IB_API_TOKEN: ${{ vars.SOURCE_IB_API_TOKEN }}
        TARGET_IB_HOST: ${{ secrets.TARGET_IB_HOST }}
        SOURCE_IB_HOST: ${{ vars.SOURCE_IB_HOST }}
        TARGET_IB_PATH: ${{ vars.TARGET_IB_PATH }}
        SOURCE_WORKING_DIR: ${{ secrets.SOURCE_WORKING_DIR }}
        DEV_IB_HOSTSOURCE_SOLUTION_DIR: ${{ vars.SOURCE_SOLUTION_DIR }}
        SOURCE_COMPILED_SOLUTIONS_PATH: ${{ vars.SOURCE_COMPILED_SOLUTIONS_PATH }}
        LOCAL_SOLUTION_DIR: ${{ vars.LOCAL_SOLUTION_DIR }}
        REL_FLOW_PATH: ${{ vars.REL_FLOW_PATH }}

      run: |
        ib-cicd --local_flow --download_ibsolution --set_github_actions_env_var

    - name: Create release and upload artifacts
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.PACKAGE_VERSION }}
        artifacts: "*.ibsolution"