name: Remote Solution Promotion

on: workflow_dispatch

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Upload and compile IB solution
      env:
        TARGET_IB_API_TOKEN: ${{ secrets.TARGET_IB_API_TOKEN }}
        SOURCE_IB_API_TOKEN: ${{ vars.SOURCE_IB_API_TOKEN }}
        TARGET_IB_HOST: ${{ secrets.TARGET_IB_HOST }}
        SOURCE_IB_HOST: ${{ vars.SOURCE_IB_HOST }}
        TARGET_IB_PATH: ${{ vars.TARGET_IB_PATH }}
        SOURCE_WORKING_DIR: ${{ secrets.SOURCE_WORKING_DIR }}
        SOURCE_SOLUTION_DIR: ${{ vars.SOURCE_SOLUTION_DIR }}
        SOURCE_COMPILED_SOLUTIONS_PATH: ${{ vars.SOURCE_COMPILED_SOLUTIONS_PATH }}
        LOCAL_SOLUTION_DIR: ${{ vars.LOCAL_SOLUTION_DIR }}
        REL_FLOW_PATH: ${{ vars.REL_FLOW_PATH }}
        
      run: |
        python -u ib_cicd/promote_sb_solution.py --remote_flow --download_ibsolution --set_github_actions_env_var

    - name: Commit changes
      run: |
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git config --global --add safe.directory /__w/${{ github.event.repository.name }}/*
        git add '*.ibsolution'
        git commit -m "Add ibsolution file"
        git tag -a ${{ env.PACKAGE_VERSION }}
        git push
        echo ${{ env.PACKAGE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create release and upload artifacts
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.PACKAGE_VERSION }}
        artifacts: "*.ibsolution"