name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        name: Format with black
        id: action_black
        with:
          options: "--verbose"
          src: "./cicd"