name: Python Checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r test-requirements.txt
      - name: Run tests
        run: |
          python -m pytest tests
#      - name: Test
#        run: tox
